env = SConscript(
    "godot-cpp/SConstruct",
    {"api_version": "4.7"}
)

env.Append(CPPPATH=["src/"])

sources = Glob("src/*.cpp")

library = env.SharedLibrary(
    "../../addons/menu_optimizer/bin/windows/menu_optimizer"
    + env["suffix"]
    + env["SHLIBSUFFIX"],
    source=sources
)

Default(library)